# Generated by Django 3.1.5 on 2021-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210125_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Winter Wear', 'Winter Wear'), ('Sports', 'Sports'), ('Casuals', 'Casuals')], default='Sports', max_length=20),
            preserve_default=False,
        ),
    ]
