# Generated by Django 3.1.5 on 2021-01-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
