# Generated by Django 3.1.5 on 2021-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderincart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
