# Generated by Django 3.1.5 on 2021-02-13 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('house_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=50)),
                ('colony', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office')], max_length=10)),
                ('payment_method', models.CharField(choices=[('CREDIT/DEBIT CARD', 'Credit/Debit Cards'), ('NET BANKING', 'Net Banking'), ('UPI', 'UPI')], max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
